#!/usr/bin/env python3
"""
eol_check.py — End-of-Life / End-of-Support lookup for detected tech stack.

Looks up each detected technology against the public endoflife.date API and
produces a per-engagement `eol.md` plus a JSON artefact summarising whether
the deployed software is still supported, near EOL, or already past it.
This feeds:

  • Phase 4 CVE prioritisation in hunt.py — past-EOL stacks score higher.
  • intel.md generated by intel.py — "Lifecycle Status" section is prepended.
  • The final VAPT report — gives PCI-DSS 6.2 / ISO 27001 A.12.6.1 evidence
    when the deployment is past vendor support.

Data source
-----------
All lifecycle data is fetched from https://endoflife.date/ (project run by
Marcel van Lohuizen / Adarsh Pyarelal and contributors, MIT-licensed,
https://github.com/endoflife-date/endoflife.date). The public JSON API at
https://endoflife.date/api/<product>.json is hit at most once per
`CACHE_TTL` seconds (default 24h) per product. **Please credit
endoflife.date in any report that uses this output.** The output writers
in this module embed that credit automatically.

Usage
-----
    python3 eol_check.py --tech "asp.net,iis,dotnetfx,php=8.1" --target host.example.com
    python3 eol_check.py --tech "wordpress=5.8,nginx=1.18" --target X --json out.json
    python3 eol_check.py --list-products            # show what we map to
    python3 eol_check.py --refresh --tech "ubuntu"  # bust cache and re-fetch

Versions can be supplied as `tech=version` (e.g. `php=7.4.33`,
`dotnetfx=4.8`); when omitted, the lookup returns the full lifecycle
table for the product so the analyst can pick the relevant cycle.

No traffic is sent to the engagement target — endoflife.date is a public
metadata source.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import ssl
import sys
import time
import urllib.error
import urllib.request
from datetime import datetime, timezone

# ─── Constants ────────────────────────────────────────────────────────────────
ENDOFLIFE_BASE = "https://endoflife.date/api"
ENDOFLIFE_HOMEPAGE = "https://endoflife.date/"
ENDOFLIFE_CREDIT = (
    "Lifecycle data courtesy of endoflife.date "
    f"({ENDOFLIFE_HOMEPAGE}) — MIT licensed, please credit when redistributing."
)
CACHE_DIR = os.path.expanduser("~/.cache/vikramaditya/eol")
CACHE_TTL = 24 * 3600  # seconds
HTTP_TIMEOUT = 10
EOL_SOON_DAYS = 90  # cycles within this window count as "support ending soon"

# macOS/Python sometimes lacks system SSL certs; fall back to certifi if present.
_SSL_CTX = ssl.create_default_context()
try:
    import certifi
    _SSL_CTX = ssl.create_default_context(cafile=certifi.where())
except ImportError:
    pass

# ─── ANSI ────────────────────────────────────────────────────────────────────
RED = "\033[91m"; YELLOW = "\033[93m"; GREEN = "\033[92m"
CYAN = "\033[96m"; BOLD = "\033[1m"; DIM = "\033[2m"; RESET = "\033[0m"

# ─── Tech fingerprint → endoflife.date product slug ──────────────────────────
# Keys are lowercased fingerprint terms (whatweb/httpx/wappalyzer style).
# Values are valid endoflife.date slugs (verified against /api/all.json).
PRODUCT_MAP: dict[str, str] = {
    # Microsoft stack
    "asp.net":           "dotnetfx",   # ASP.NET on .NET Framework — most common with IIS
    "aspnet":            "dotnetfx",
    "asp.net core":      "dotnet",
    "aspnetcore":        "dotnet",
    ".net":              "dotnet",
    ".net framework":    "dotnetfx",
    "dotnet":            "dotnet",
    "dotnetcore":        "dotnet",
    "dotnetfx":          "dotnetfx",
    "dotnetframework":   "dotnetfx",
    "iis":               "windows-server",   # IIS lifecycle = host Windows Server
    "microsoft-iis":     "windows-server",
    "windows":           "windows",
    "windows server":    "windows-server",
    "windows-server":    "windows-server",
    "powershell":        "windows-powershell",

    # Web servers
    "apache":            "apache-http-server",
    "apache httpd":      "apache-http-server",
    "httpd":             "apache-http-server",
    "nginx":             "nginx",
    "tomcat":            "tomcat",
    "apache tomcat":     "tomcat",
    "caddy":             "caddy",

    # Languages / runtimes
    "php":               "php",
    "python":            "python",
    "node.js":           "nodejs",
    "nodejs":            "nodejs",
    "node":              "nodejs",
    "ruby":              "ruby",
    "perl":              "perl",
    "go":                "go",
    "golang":            "go",
    "rust":              "rust",
    "java":              "java",
    "openjdk":           "azul-zulu",   # closest LTS-aligned slug
    "kotlin":            "kotlin",
    "bun":               "bun",

    # Frameworks / CMS
    "wordpress":         "wordpress",
    "drupal":            "drupal",
    "phpbb":             "phpbb",
    "phpmyadmin":        "phpmyadmin",
    "rails":             "rails",
    "ruby on rails":     "rails",
    "django":            "django",
    "laravel":           "laravel",
    "symfony":           "symfony",
    "cakephp":           "cakephp",
    "next.js":           "nextjs",
    "nextjs":            "nextjs",
    "angular":           "angular",
    "angularjs":         "angularjs",
    "react":             "react",
    "vue":               "vue",
    "vue.js":            "vue",
    "svelte":            "svelte",
    "spring":            "spring-framework",
    "spring boot":       "spring-boot",
    "spring-boot":       "spring-boot",
    "spring framework":  "spring-framework",
    "spring security":   "spring-security",
    "apache struts":     "apache-struts",
    "struts":            "apache-struts",

    # Databases / caches
    "mysql":             "mysql",
    "mariadb":           "mariadb",
    "postgresql":        "postgresql",
    "postgres":          "postgresql",
    "mongodb":           "mongodb",
    "mongo":             "mongodb",
    "redis":             "redis",
    "elasticsearch":     "elasticsearch",
    "kibana":            "kibana",
    "logstash":          "logstash",
    "cassandra":         "apache-cassandra",
    "couchdb":           "apache-couchdb",
    "rabbitmq":          "rabbitmq",
    "kafka":             "apache-kafka",

    # Linux distros
    "ubuntu":            "ubuntu",
    "debian":            "debian",
    "centos":            "centos",
    "centos stream":     "centos-stream",
    "rhel":              "rhel",
    "redhat":            "rhel",
    "red hat":           "rhel",
    "rocky":             "rocky-linux",
    "rocky linux":       "rocky-linux",
    "alma":              "almalinux",
    "almalinux":         "almalinux",
    "alpine":            "alpine-linux",
    "amazon linux":      "amazon-linux",
    "amazon-linux":      "amazon-linux",
    "amzn":              "amazon-linux",

    # Cloud / orchestration / runtime
    "kubernetes":        "kubernetes",
    "k8s":               "kubernetes",
    "docker":            "docker-engine",
    "openshift":         "openshift",
    "amazon eks":        "amazon-eks",
    "azure aks":         "azure-kubernetes-service",
    "amazon rds mysql":  "amazon-rds-mysql",
    "amazon rds postgres": "amazon-rds-postgresql",
    "amazon aurora postgres": "amazon-aurora-postgresql",
    "aws lambda":        "aws-lambda",

    # Mobile
    "android":           "android",
    "ios":               "ios",
    "macos":             "macos",
}


# ─── Cache helpers ────────────────────────────────────────────────────────────
def _cache_path(slug: str) -> str:
    os.makedirs(CACHE_DIR, exist_ok=True)
    return os.path.join(CACHE_DIR, f"{slug}.json")


def _load_cached(slug: str, ttl: int = CACHE_TTL) -> list[dict] | None:
    path = _cache_path(slug)
    if not os.path.exists(path):
        return None
    if (time.time() - os.path.getmtime(path)) > ttl:
        return None
    try:
        with open(path) as f:
            return json.load(f)
    except (json.JSONDecodeError, OSError):
        return None


def _store_cached(slug: str, data: list[dict]) -> None:
    try:
        with open(_cache_path(slug), "w") as f:
            json.dump(data, f, indent=2)
    except OSError:
        pass


# ─── HTTP fetch ──────────────────────────────────────────────────────────────
def fetch_product_cycles(slug: str, refresh: bool = False) -> list[dict] | None:
    """
    Return the list of lifecycle cycles for `slug`, or None on hard error /
    unknown product. Cached for CACHE_TTL seconds.
    """
    if not refresh:
        cached = _load_cached(slug)
        if cached is not None:
            return cached

    url = f"{ENDOFLIFE_BASE}/{slug}.json"
    req = urllib.request.Request(url, headers={
        "User-Agent": "Vikramaditya-EOLcheck/1.0 (+https://endoflife.date credited)",
        "Accept": "application/json",
    })
    try:
        with urllib.request.urlopen(req, timeout=HTTP_TIMEOUT, context=_SSL_CTX) as resp:
            data = json.load(resp)
    except urllib.error.HTTPError as e:
        if e.code == 404:
            # Unknown product — cache the negative so we don't re-hit
            _store_cached(slug, [])
            return []
        return None
    except (urllib.error.URLError, TimeoutError, json.JSONDecodeError):
        return None

    _store_cached(slug, data)
    return data


# ─── Version matching ────────────────────────────────────────────────────────
_VER_RE = re.compile(r"\d+(?:\.\d+){0,3}")


def _normalize(v: str) -> tuple[int, ...]:
    parts = []
    for chunk in v.split("."):
        m = re.match(r"(\d+)", chunk)
        parts.append(int(m.group(1)) if m else 0)
    return tuple(parts)


def _match_cycle(cycles: list[dict], version: str) -> dict | None:
    """
    Find the cycle whose `cycle` field is a prefix of the supplied version,
    favouring the longest matching prefix. Falls back to the first cycle
    when no match is found.
    """
    if not cycles:
        return None
    if not version:
        return None
    v_norm = _normalize(version)
    best = None
    best_len = -1
    for c in cycles:
        cyc = str(c.get("cycle", "")).strip()
        if not cyc:
            continue
        c_norm = _normalize(cyc)
        if v_norm[: len(c_norm)] == c_norm and len(c_norm) > best_len:
            best = c
            best_len = len(c_norm)
    return best


def _classify_eol(cycle: dict) -> tuple[str, int | None]:
    """
    Returns (status, days_to_eol).
    status ∈ {"supported", "soon", "expired", "unknown"}.
    """
    eol = cycle.get("eol")
    if eol is False:
        return ("supported", None)
    if eol is True:
        return ("expired", None)
    if isinstance(eol, str):
        try:
            eol_dt = datetime.strptime(eol, "%Y-%m-%d").replace(tzinfo=timezone.utc)
        except ValueError:
            return ("unknown", None)
        now = datetime.now(timezone.utc)
        delta = (eol_dt - now).days
        if delta < 0:
            return ("expired", delta)
        if delta <= EOL_SOON_DAYS:
            return ("soon", delta)
        return ("supported", delta)
    return ("unknown", None)


# ─── Public API ──────────────────────────────────────────────────────────────
def lookup(tech_term: str, version: str | None = None,
           refresh: bool = False) -> dict:
    """
    Resolve a fingerprint term and (optional) version into a lifecycle entry.

    Returns:
        {
          "tech": original tech_term,
          "slug": endoflife.date slug or None,
          "version": version or None,
          "matched_cycle": cycle dict or None,
          "cycle_inferred": bool,   # True = cycle was a guess (no version),
                                    #        not matched to the supplied version
          "status": "supported" | "soon" | "expired" | "unknown" | "no_data",
          "days_to_eol": int or None,
          "latest": str or None,    # latest patch in matched cycle
          "eol_date": str or None,  # raw eol value from feed
          "all_cycles": list[dict],
          "credit": ENDOFLIFE_CREDIT,
        }
    """
    key = tech_term.strip().lower()
    slug = PRODUCT_MAP.get(key)
    if not slug:
        # Try a tolerant fallback — strip dashes/dots
        key2 = re.sub(r"[ .\-_/]", "", key)
        for k, v in PRODUCT_MAP.items():
            if re.sub(r"[ .\-_/]", "", k) == key2:
                slug = v
                break

    out: dict = {
        "tech": tech_term, "slug": slug, "version": version,
        "matched_cycle": None, "status": "no_data",
        "days_to_eol": None, "latest": None, "eol_date": None,
        "all_cycles": [], "credit": ENDOFLIFE_CREDIT,
    }
    if not slug:
        return out

    cycles = fetch_product_cycles(slug, refresh=refresh)
    if cycles is None:
        out["status"] = "unknown"
        return out
    out["all_cycles"] = cycles
    if not cycles:
        return out  # 404 / empty product

    matched = _match_cycle(cycles, version) if version else None
    if version and matched is None:
        # A version was supplied but no cycle's label is a numeric prefix of it
        # (e.g. php=5 against cycles 5.6/7.x/8.x). Do NOT fall back to the newest
        # cycle and classify against it — that fabricates a "supported" verdict
        # for software that may be long EOL. Surface the unmatched state instead.
        out["status"] = "unknown"
        out["matched_cycle"] = None
        out["cycle_inferred"] = False
        return out
    if matched is None:
        # No version supplied: use the most recent cycle as a hint only, and
        # flag that the cycle was inferred rather than matched to a version.
        matched = cycles[0]
        out["cycle_inferred"] = True
    else:
        out["cycle_inferred"] = False
    out["matched_cycle"] = matched
    out["latest"] = matched.get("latest")
    out["eol_date"] = matched.get("eol")
    status, days = _classify_eol(matched)
    out["status"] = status
    out["days_to_eol"] = days
    return out


def lookup_many(techs: list[tuple[str, str | None]],
                refresh: bool = False) -> list[dict]:
    return [lookup(t, v, refresh=refresh) for t, v in techs]


# ─── Output writers ──────────────────────────────────────────────────────────
_STATUS_ICON = {
    "expired":   "🔴 EOL — past vendor support",
    "soon":      "🟠 Support ending soon",
    "supported": "🟢 Supported",
    "unknown":   "⚪ Unknown",
    "no_data":   "⚪ Not tracked by endoflife.date",
}


def build_markdown(results: list[dict], target: str = "") -> str:
    lines = [
        "# Lifecycle / End-of-Life Status",
        "",
    ]
    if target:
        lines.append(f"**Target:** `{target}`")
    lines += [
        f"**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M %Z').strip()}",
        f"**Source:** [endoflife.date]({ENDOFLIFE_HOMEPAGE}) — public lifecycle metadata API",
        "",
        "| Tech | Slug | Version | Status | EOL | Latest | Days to EOL |",
        "|---|---|---|---|---|---|---|",
    ]
    for r in results:
        status = _STATUS_ICON.get(r["status"], r["status"])
        days = r["days_to_eol"]
        days_s = "—" if days is None else (f"{days}" if days >= 0 else f"{days} (expired)")
        lines.append(
            "| {tech} | `{slug}` | {ver} | {st} | {eol} | {latest} | {days} |".format(
                tech=r["tech"],
                slug=r["slug"] or "—",
                ver=r["version"] or "—",
                st=status,
                eol=r["eol_date"] if r["eol_date"] not in (None, False, True) else (
                    "supported" if r["eol_date"] is False else
                    "expired" if r["eol_date"] is True else "—"
                ),
                latest=r["latest"] or "—",
                days=days_s,
            )
        )
    lines += [
        "",
        "---",
        "",
        f"_{ENDOFLIFE_CREDIT}_",
        "",
    ]
    # Per-tech expanded cycle table for context
    for r in results:
        if not r["all_cycles"]:
            continue
        lines += [
            f"### Lifecycle cycles — `{r['slug']}` ({r['tech']})",
            "",
            "| Cycle | Released | LTS | EOL | Latest | Latest Released |",
            "|---|---|---|---|---|---|",
        ]
        for c in r["all_cycles"][:12]:
            eol = c.get("eol")
            eol_s = "supported" if eol is False else "expired" if eol is True else (eol or "—")
            lines.append(
                "| `{cyc}` | {rel} | {lts} | {eol} | {lat} | {latrel} |".format(
                    cyc=c.get("cycle", "—"),
                    rel=c.get("releaseDate", "—"),
                    lts="✅" if c.get("lts") else "—",
                    eol=eol_s,
                    lat=c.get("latest", "—"),
                    latrel=c.get("latestReleaseDate", "—"),
                )
            )
        lines.append("")

    return "\n".join(lines)


# ─── CLI ─────────────────────────────────────────────────────────────────────
def _parse_tech_arg(arg: str) -> list[tuple[str, str | None]]:
    """Parse 'php=8.1,nginx=1.18,asp.net' into [(tech, version), ...]."""
    out: list[tuple[str, str | None]] = []
    for part in arg.split(","):
        part = part.strip()
        if not part:
            continue
        if "=" in part:
            t, v = part.split("=", 1)
            out.append((t.strip(), v.strip()))
        else:
            out.append((part, None))
    return out


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--tech", help="Comma-separated techs (e.g. 'asp.net,iis,php=8.1')")
    p.add_argument("--target", default="", help="Target name for output dir")
    p.add_argument("--output", default="", help="Markdown output path (default: recon/<target>/eol.md)")
    p.add_argument("--json", default="", help="JSON output path (optional)")
    p.add_argument("--refresh", action="store_true", help="Bust the 24h cache and re-fetch")
    p.add_argument("--list-products", action="store_true", help="Print known fingerprint→slug map and exit")
    p.add_argument("--quiet", action="store_true")
    args = p.parse_args()

    if args.list_products:
        for k, v in sorted(PRODUCT_MAP.items()):
            print(f"  {k:<24} → {v}")
        print(f"\n{ENDOFLIFE_CREDIT}")
        return 0

    if not args.tech:
        p.error("--tech is required (or use --list-products)")

    techs = _parse_tech_arg(args.tech)
    if not args.quiet:
        print(f"\n{BOLD}Lifecycle / EOL check (data: endoflife.date){RESET}")
        print(f"Target  : {CYAN}{args.target or '(unspecified)'}{RESET}")
        print(f"Techs   : {CYAN}{', '.join(t + (f'={v}' if v else '') for t, v in techs)}{RESET}")
        print()

    results = lookup_many(techs, refresh=args.refresh)

    if not args.quiet:
        for r in results:
            colour = {
                "expired":  RED, "soon": YELLOW,
                "supported": GREEN, "unknown": DIM, "no_data": DIM,
            }.get(r["status"], "")
            ver = f"={r['version']}" if r["version"] else ""
            slug = r["slug"] or "(unmapped)"
            print(f"  {colour}[{r['status'].upper():<9}]{RESET} "
                  f"{r['tech']}{ver}  → slug={slug}  "
                  f"latest={r['latest'] or '—'}  eol={r['eol_date']}  "
                  f"days_to_eol={r['days_to_eol']}")

    md_path = args.output
    if not md_path:
        if args.target:
            base = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                                "recon", args.target)
            os.makedirs(base, exist_ok=True)
            md_path = os.path.join(base, "eol.md")
        else:
            md_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "eol.md")

    md = build_markdown(results, target=args.target)
    with open(md_path, "w") as f:
        f.write(md)
    if not args.quiet:
        print(f"\n  {GREEN}Markdown:{RESET} {md_path}")

    if args.json:
        # Strip the bulky all_cycles list from the per-tech JSON to keep it small
        slim = []
        for r in results:
            slim.append({k: v for k, v in r.items() if k != "all_cycles"})
        with open(args.json, "w") as f:
            json.dump({
                "target": args.target,
                "generated": datetime.now(timezone.utc).isoformat(),
                "credit": ENDOFLIFE_CREDIT,
                "results": slim,
            }, f, indent=2)
        if not args.quiet:
            print(f"  {GREEN}JSON    :{RESET} {args.json}")

    if not args.quiet:
        print(f"\n{DIM}{ENDOFLIFE_CREDIT}{RESET}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
